const dishes = [
  {
    name: "Romige champignonpasta",
    diet: "veg",
    time: "mid",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "Comfort", "30 min"],
    ingredients: ["pasta", "champignons", "room", "knoflook", "peterselie"],
  },
  {
    name: "Geroosterde groentesalade met feta",
    diet: "veg",
    time: "mid",
    mood: ["fresh"],
    style: "med",
    tags: ["Fris", "Oven", "30 min"],
    ingredients: ["paprika", "courgette", "rode ui", "feta", "citroen"],
  },
  {
    name: "Zoete aardappel taco's",
    diet: "vegan",
    time: "mid",
    mood: ["spicy", "fresh"],
    style: "latam",
    tags: ["Vegan", "Pittig", "30 min"],
    ingredients: ["zoete aardappel", "taco's", "bonen", "limoen", "koriander"],
  },
  {
    name: "Aziatische noedelbowl met tofu",
    diet: "vegan",
    time: "quick",
    mood: ["fresh"],
    style: "asian",
    tags: ["Vegan", "Snel", "20 min"],
    ingredients: ["noedels", "tofu", "sojasaus", "bosui", "sesam"],
  },
  {
    name: "Zalm uit de oven met citroen",
    diet: "pesc",
    time: "mid",
    mood: ["protein"],
    style: "med",
    tags: ["Pescatarisch", "Eiwit", "30 min"],
    ingredients: ["zalm", "citroen", "knoflook", "dille", "aardappeltjes"],
  },
  {
    name: "Shakshuka met brood",
    diet: "veg",
    time: "mid",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "Comfort", "30 min"],
    ingredients: ["tomaten", "eieren", "paprika", "ui", "brood"],
  },
  {
    name: "Poke bowl met zalm en edamame",
    diet: "pesc",
    time: "quick",
    mood: ["fresh", "protein"],
    style: "asian",
    tags: ["Pescatarisch", "Snel", "20 min"],
    ingredients: ["zalm", "rijst", "edamame", "komkommer", "sojasaus"],
  },
  {
    name: "Kip teriyaki met broccoli",
    diet: "all",
    time: "mid",
    mood: ["protein"],
    style: "asian",
    tags: ["Eiwit", "30 min"],
    ingredients: ["kip", "broccoli", "rijst", "teriyakisaus"],
  },
  {
    name: "Spaghetti met pittige tomatensaus",
    diet: "veg",
    time: "quick",
    mood: ["spicy"],
    style: "med",
    tags: ["Vegetarisch", "Pittig", "20 min"],
    ingredients: ["spaghetti", "tomaten", "chili", "knoflook", "parmezaan"],
  },
  {
    name: "Stampot zoete aardappel",
    diet: "veg",
    time: "slow",
    mood: ["comfort"],
    style: "nl",
    tags: ["Nederlands", "Comfort", "45 min"],
    ingredients: ["zoete aardappel", "boerenkool", "boter", "mosterd"],
  },
  {
    name: "Kikkererwten curry met spinazie",
    diet: "vegan",
    time: "mid",
    mood: ["spicy", "comfort"],
    style: "asian",
    tags: ["Vegan", "Kruiden", "35 min"],
    ingredients: ["kikkererwten", "spinazie", "kokosmelk", "currypasta"],
  },
  {
    name: "Tuna melt sandwich",
    diet: "pesc",
    time: "quick",
    mood: ["comfort"],
    style: "nl",
    tags: ["Pescatarisch", "Snel", "15 min"],
    ingredients: ["tonijn", "brood", "kaas", "rode ui"],
  },
  {
    name: "Buddha bowl met quinoa",
    diet: "vegan",
    time: "mid",
    mood: ["fresh"],
    style: "med",
    tags: ["Vegan", "Fris", "30 min"],
    ingredients: ["quinoa", "avocado", "kikkererwten", "spinazie", "citroen"],
  },
  {
    name: "Gnocchi met pesto en tomaat",
    diet: "veg",
    time: "quick",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "Snel", "20 min"],
    ingredients: ["gnocchi", "pesto", "cherrytomaat", "parmezaan"],
  },
  {
    name: "Burrito bowl met zwarte bonen",
    diet: "vegan",
    time: "mid",
    mood: ["protein"],
    style: "latam",
    tags: ["Vegan", "Eiwit", "30 min"],
    ingredients: ["zwarte bonen", "rijst", "maïs", "paprika", "limoen"],
  },
  {
    name: "Saté met pindasaus en rijst",
    diet: "all",
    time: "slow",
    mood: ["comfort", "protein"],
    style: "asian",
    tags: ["Eiwit", "45 min"],
    ingredients: ["kip", "pindasaus", "rijst", "komkommer"],
  },
  {
    name: "Salade niçoise",
    diet: "pesc",
    time: "mid",
    mood: ["fresh", "protein"],
    style: "med",
    tags: ["Fris", "30 min"],
    ingredients: ["tonijn", "eieren", "sperziebonen", "olijven"],
  },
  {
    name: "Rijstbowl met falafel",
    diet: "veg",
    time: "quick",
    mood: ["fresh"],
    style: "med",
    tags: ["Vegetarisch", "Snel", "20 min"],
    ingredients: ["falafel", "rijst", "komkommer", "yoghurt", "munt"],
  },
  {
    name: "Chili sin carne",
    diet: "vegan",
    time: "slow",
    mood: ["spicy", "comfort"],
    style: "latam",
    tags: ["Vegan", "Pittig", "45 min"],
    ingredients: ["kidneybonen", "tomaten", "paprika", "chili", "maïs"],
  },
  {
    name: "Ovenschotel met broccoli en kaas",
    diet: "veg",
    time: "slow",
    mood: ["comfort"],
    style: "nl",
    tags: ["Vegetarisch", "Oven", "45 min"],
    ingredients: ["broccoli", "aardappels", "kaas", "room"],
  },
  {
    name: "Ramen met miso en ei",
    diet: "pesc",
    time: "mid",
    mood: ["comfort"],
    style: "asian",
    tags: ["Comfort", "35 min"],
    ingredients: ["ramen", "miso", "eieren", "bosui", "spinazie"],
  },
  {
    name: "Groene curry met groenten",
    diet: "vegan",
    time: "mid",
    mood: ["spicy"],
    style: "asian",
    tags: ["Vegan", "Pittig", "30 min"],
    ingredients: ["kokosmelk", "groene curry", "broccoli", "sugarsnaps"],
  },
  {
    name: "Tortilla pizza met pesto",
    diet: "veg",
    time: "quick",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "Snel", "15 min"],
    ingredients: ["tortilla", "pesto", "mozzarella", "tomaat"],
  },
  {
    name: "Nasi met groenten en ei",
    diet: "veg",
    time: "mid",
    mood: ["comfort"],
    style: "asian",
    tags: ["Comfort", "30 min"],
    ingredients: ["rijst", "wokgroenten", "eieren", "ketjap"],
  },
  {
    name: "Gegrilde halloumi bowl",
    diet: "veg",
    time: "mid",
    mood: ["fresh"],
    style: "med",
    tags: ["Vegetarisch", "Fris", "30 min"],
    ingredients: ["halloumi", "couscous", "tomaat", "komkommer"],
  },
  {
    name: "Wraps met kip en avocado",
    diet: "all",
    time: "quick",
    mood: ["fresh", "protein"],
    style: "latam",
    tags: ["Snel", "Eiwit", "20 min"],
    ingredients: ["wraps", "kip", "avocado", "sla"],
  },
  {
    name: "Pompoensoep met brood",
    diet: "vegan",
    time: "slow",
    mood: ["comfort"],
    style: "nl",
    tags: ["Vegan", "Soep", "45 min"],
    ingredients: ["pompoen", "ui", "knoflook", "kokosmelk"],
  },
  {
    name: "Caprese pasta salade",
    diet: "veg",
    time: "quick",
    mood: ["fresh"],
    style: "med",
    tags: ["Vegetarisch", "Fris", "20 min"],
    ingredients: ["pasta", "mozzarella", "tomaat", "basilicum"],
  },
  {
    name: "Vis taco's met mango",
    diet: "pesc",
    time: "mid",
    mood: ["fresh"],
    style: "latam",
    tags: ["Pescatarisch", "Fris", "30 min"],
    ingredients: ["witvis", "taco's", "mango", "kool"],
  },
  {
    name: "Rijst met linzen en yoghurt",
    diet: "veg",
    time: "mid",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "35 min"],
    ingredients: ["linzen", "rijst", "yoghurt", "komijn"],
  },
  {
    name: "Gevulde paprika's",
    diet: "veg",
    time: "slow",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "Oven", "45 min"],
    ingredients: ["paprika", "rijst", "feta", "tomaat"],
  },
  {
    name: "Sushibowl met komkommer",
    diet: "vegan",
    time: "quick",
    mood: ["fresh"],
    style: "asian",
    tags: ["Vegan", "Snel", "20 min"],
    ingredients: ["sushirijst", "komkommer", "zeewier", "sojasaus"],
  },
  {
    name: "Hollandse erwtensoep",
    diet: "all",
    time: "slow",
    mood: ["comfort"],
    style: "nl",
    tags: ["Nederlands", "45 min"],
    ingredients: ["spliterwten", "wortel", "prei", "rookworst"],
  },
  {
    name: "Courgette fritters met tzatziki",
    diet: "veg",
    time: "mid",
    mood: ["fresh"],
    style: "med",
    tags: ["Vegetarisch", "30 min"],
    ingredients: ["courgette", "eieren", "meel", "yoghurt"],
  },
  {
    name: "Soba noedels met pinda",
    diet: "vegan",
    time: "quick",
    mood: ["spicy"],
    style: "asian",
    tags: ["Vegan", "Snel", "20 min"],
    ingredients: ["soba", "pindakaas", "sojasaus", "limoen"],
  },
  {
    name: "Mediterrane plaatpizza",
    diet: "veg",
    time: "slow",
    mood: ["comfort"],
    style: "med",
    tags: ["Vegetarisch", "Oven", "45 min"],
    ingredients: ["pizzadeeg", "olijven", "tomaat", "mozzarella"],
  },
  {
    name: "Zwarte bonensoep",
    diet: "vegan",
    time: "slow",
    mood: ["comfort"],
    style: "latam",
    tags: ["Vegan", "Soep", "45 min"],
    ingredients: ["zwarte bonen", "tomaten", "ui", "komijn"],
  },
];
